### ISSUE TITLE
Sort By Size

### ISSUE THREAD

**Issue by Azertick** [M1n-74316D65/Wabbajack-fast-downloader#1]
I decided to use your software and I did like it but I ended up re writing it to take the size from the modlist as well and sort from least to greatest like wabbajack and get the mass out before I got to any large downloads, I think it would be great if you added it to the default script.

**Comment by M1n-74316D65** [comment]
I'm just putting it together and doing the README. I don't plan on touching the code, as it's not my code. Sorry.

**Comment by SasukiHardAss** [comment]
@Azertick can you share the script if you don't mind ?
