### ISSUE TITLE
Problems on URL renaming

### ISSUE THREAD

**Issue by merrkry** [M1n-74316D65/Wabbajack-fast-downloader#2]
1. URL renaming should be in the 4th step "Extract Modlist Data", and it is `extract_modlist` that should be modifield.
2. It is usual to have files from different games in a single modlist file. So it will be more compatible to get game name from `modlist` file instead of using a fixed value. It can be found under key `Meta`, which is a string formated as INI.

**Comment by M1n-74316D65** [comment]
I'm just putting it together and doing the README. I don't plan on touching the code, as it's not my code. Sorry.
