### ISSUE TITLE
Can you make this for modlist in the nexusmods collection?

### ISSUE THREAD

**Issue by qweqwedasdas** [M1n-74316D65/Wabbajack-fast-downloader#3]
Can you make this for modlist in the nexusmods collection?

**Comment by M1n-74316D65** [comment]
Sorry, I don't use Vortex, but you can use this in your browser, so you can skip the 5 s:

- [Tampermonkey](https://www.tampermonkey.net/)

- [Tampermonkey plugin that removes Nexus Mods wait time](https://greasyfork.org/en/scripts/394039-nexus-no-wait)
