### ISSUE TITLE
New Feature to keep track of all opened batch downloads incase of resuming later after closing program (enhancement)

### ISSUE THREAD

**Issue by CrimsonDemo** [M1n-74316D65/Wabbajack-fast-downloader#4]
I want to suggest a feature for this awesome program which is helping me in downloading a 3600 mods list to keep track of all its previously opened batch downloads so that if this program ever shuts-down, it has a log to know how many of the batches have been opened before, since it is my understanding that this program only opens batches of 20 and has no correlation to the actual download which the tampermonkey script does. It would be very helpful for it to do this.

**Comment by M1n-74316D65** [comment]
I'm just putting it together and doing the README. I don't plan on touching the code, as it's not my code.
